fix student_id in database
ILMOWEB/ilmo pull request #172
Opened 2023-11-28 13:38 UTC by ellaverak

fix the way student id is saved to the official database and add functionality to db_admin

2023-11-29 11:30 UTC, sohvip commented on app/config/db_admin.py
> +fucntion = input("Lisää superuser1, Poista käyttäjä 2: ")
onko tossa  muuttujassa kirjoitusvirhe vai tahallaan "fucntion"?

2023-11-29 11:32 UTC, sohvip requested changes
yks kysymys siellä kommenteissa.

2023-11-29 12:02 UTC, ellaverak commented on app/config/db_admin.py
> +fucntion = input("Lisää superuser1, Poista käyttäjä 2: ")
Siinä on kirjotusvirhe 😂
Korjaan sen illalla ku ehdin, mut pääsen varmaan vasta aika myöhään koneen ääreen

2023-11-30 06:26 UTC, sohvip approved these changes
good

2023-11-30 06:27 UTC, merged