Testing instructions
ILMOWEB/ilmo pull request #201
Opened 2023-12-12 17:22 UTC by mirellel

- added testing instructions in documentation/testing.md
- updated README to have a link to testing instructions and deleted the testing instructions from README

2023-12-13 14:12 UTC, sohvip requested changes
fix the typos, then it's PERFECT

2023-12-13 14:12 UTC, sohvip commented on README.md
> +- [Testing instuctions](https://github.com/ILMOWEB/ilmo/blob/main/documentation/testing.md)
*instructions (typo)

2023-12-13 14:12 UTC, sohvip commented on documentation/testing.md
> +Currert coverage:
maybe it should be current?

2023-12-14 11:36 UTC, Noraelisa approved these changes
Yes perfect! :)

2023-12-14 11:36 UTC, Noraelisa approved these changes

2023-12-14 11:38 UTC, Noraelisa approved these changes

2023-12-14 11:38 UTC, Noraelisa approved these changes

2023-12-14 11:44 UTC, merged